### ISSUE TITLE
希望可以公布一个数据解析的接口出来

### ISSUE THREAD

**Issue by cdoky** [JxbSir/JxbDebugTool#2]
原因：数据加密，想要显示解密后的数据

**Comment by JxbSir** [comment]
pod 'JxbDebugTool', '~> 4.2'

增加3个属性, 设置好delegate，实现- (NSData_)decryptJson:(NSData_)data;

@property (nonatomic, weak)     id<JxbDebugDelegate> delegate;
@property (nonatomic, assign)   BOOL        isHttpRequestEncrypt;
@property (nonatomic, assign)   BOOL        isHttpResponseEncrypt;
