### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by dadpp** [JxbSir/JxbDebugTool#3]
```
NSURLSession *session = [NSURLSession sharedSession];
NSURL *url = [NSURL URLWithString:@"http://api.douban.com/v2/book/isbn/9787505715660"];
NSURLSessionTask *task = [session dataTaskWithURL:url
                                completionHandler:^(NSData *data,
                                                    NSURLResponse *response,
                                                    NSError *error) {
                                    if (error) {
                                        NSLog(@"Error NSURLSession = %@",[error.userInfo objectForKey:@"NSErrorFailingURLKey"]);
                                    }else{
                                        NSLog(@"sucess NSURLSessionTask");
                                    }
                                }];

[task resume];
```

如果是这样的或者是直接用 afn 请求的就抓取不打了呀

**Comment by dadpp** [comment]
hi,上面这个是可以监听到的,但是 AFN最新版本是监控不到的

**Comment by dadpp** [comment]
#import "AFURLSessionManager+SessionConfiguration.h"
#import "CustomURLProtocol.h"
#import <objc/runtime.h>

@implementation AFURLSessionManager (SessionConfiguration)

+(void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Method from = class_getInstanceMethod([self class], @selector(initWithSessionConfiguration:));
        Method to = class_getInstanceMethod([self class], @selector(initSwizzlingSessionConfiguration:));
        if (!class_addMethod([self class], @selector(initWithSessionConfiguration:), method_getImplementation(to), method_getTypeEncoding(to))) {
            method_exchangeImplementations(from, to);
        }
    });
}

-(instancetype)initSwizzlingSessionConfiguration:(NSURLSessionConfiguration *)sessionConfigurat
{
    NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
    NSMutableArray \* protocolsArray = [sessionConfiguration.protocolClasses mutableCopy];
    [protocolsArray insertObject:[CustomURLProtocol class] atIndex:0];
    sessionConfiguration.protocolClasses = protocolsArray;

```
return [self initSwizzlingSessionConfiguration:sessionConfiguration];
```

}

AFN3.0添加这个分类就可以了,我有一个疑问,如果我打包了,但是我没有导入 AFN, 但是我又想这个分类不报错,应该怎么做呢,期待你的回答

**Comment by dadpp** [comment]
这个监控不了 ASI,CFNetwork 的都不行..看了代码了..

**Comment by JxbSir** [comment]
看到你提交的问题了，目前抽时间在调整，谢谢

**Comment by dadpp** [comment]
感恩感恩,你写的很不错,源码非常容易看明白

**Comment by JxbSir** [comment]
欢迎Pull request

**Comment by dadpp** [comment]
hi 这样的解决方案并不是完美的，我研究了，大部分人 其实都是参考 FLEX 的实现方案的 https://github.com/Flipboard/FLEX 目前这部分我已经实现啦
